spring.application.name=demo

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.chat.options.temperature=0.3
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=tecnologias
spring.ai.vectorstore.qdrant.initialize-schema=true

system.text=Eres un asistente especializado en desarrollo de software. \
Responde utilizando EXCLUSIVAMENTE la información incluida en CONTEXTO. \
\
REGLAS: \
1. No utilices conocimientos propios ni información externa al CONTEXTO. \
2. No inventes información. \
3. Si el CONTEXTO no contiene información suficiente para responder a la pregunta, devuelve exactamente un objeto JSON vacío. \
4. Si existe información suficiente, devuelve un único objeto JSON con el campo explicacion. \
5. Devuelve exclusivamente JSON válido. \
6. No incluyas markdown ni bloques de código. \
\
CONTEXTO: \
{contexto}

server.port=8001